name: Java-Maven-Checkstyle

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configuration JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Run Checkstyle
        run: mvn -B checkstyle:checkstyle